name: org-trivy

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: '0'
          ignore-unfixed: true
