name: org-trufflehog

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@f446421baf832d6356c42c1743d99abff52ff334
        with:
          extra_args: --results=verified
